### ISSUE TITLE
"graph" -> "viagra"

### ISSUE THREAD

**Issue by rrwright** [kwf/Pronunciations#5]
Hmmm… Something doesn't quite seem right about this result… :-D

```
~/Code/Pronunciations$ stack exec -- portmanteau cmu.dict graph -o 2 -r -d 1
Reading dictionary file ...
------------------------------
Group 0
Pronunciation: [Consonant G,Consonant R,Vowel AE 1,Consonant F]
----
aggrey
agra
agree
agri
agro
alegre
allegra
allegro
angry
bhangra
bocanegra
caponigro
conagra
degraw
degray
degree
delnegro
disagree
emigre
filigree
gras
grau
graue
graw
grawe
gray
graye
grew
grewe
grey
gro
groh
grow
growe
hardegree
hardigree
hungry
ingrao
integra
isgro
kingrey
lagrow
legree
loghry
lonigro
macgraw
magri
magro
mardi-gras
mcgraw
mcgray
mcgrew
migra
milagro
montenegro
mulgrew
negri
negro
niagara
nigro
outgrew
outgrow
pedigree
pellagra
pettigrew
pingree
shangri
shugrue
sinagra
sugrue
viagra
------------------------------
```

**Comment by mhuesch** [comment]
Hmm. So this seems right to me: the "-r" flag sets graph to be the second word of the portmanteau. So we would get "viagraph".

What was your expectation? There is certainly room for improvement in the help printouts :)

**Comment by rrwright** [comment]
An observation: dropping the last phoneme on some of these words makes it utterly unrecognizable as that word. I doubt you could ever systematically determine which words need their final phoneme and which don't, but just an observation.

And it might be worth filtering the list a little bit in the case of small words which actually _become_ the original word after conjunction. E.g. "gras" + "graph" = "graph"

**Comment by mhuesch** [comment]
Yes, that's definitely a concern! I'm thinking of adding the feature we discussed in person, of joining the words together phonetically and listing possible spellings.

I've used the `-m` flag (which requires a certain number of phonemes to be added to the first word) to handle the latter case. But not listing words in the first place would be an improvement.

**Comment by mhuesch** [comment]
I'm going to close this and create new issues for the other features. Thanks for your input!
